### ISSUE TITLE
closed source on gplv3 upstream project?

### ISSUE THREAD

**Issue by abale** [NanoBytesInc/Pickaxe#12]
By your own admission 

a) this project is based on xmrig
b) you are keeping it closed source

Seems like a legal issue - xmrig is GPLv3 and you have not published source... what is your position here? https://github.com/xmrig/xmrig/blob/master/LICENSE

**Comment by NanoBytesInc** [comment]
Sweetheart, put a little bit more effort into your accusations before you bear your pitchforks

https://github.com/NanoBytesInc/miners/tree/master/xmrig

The Java code that wraps around this is the part that is closed source, and I have written permission from the XMRig developers allowing this.

Check up
