### ISSUE TITLE
Still keeps crashing on custom pool

### ISSUE THREAD

**Issue by R4V3N-2010** [NanoBytesInc/Pickaxe#2]
The App crashed on if i choose Mining Pool Hub as pool.
Then i discovered that the app is also crashing on the pre filled pools.
I use a One Plus 3 with amr64-v8a architecture. Maybe you can take a look at it.

**Comment by NanoBytesInc** [comment]
Yeah, it seems that people with Exynos CPUs and a few OnePlus users are having issues. 

I am working on a fix tho! Which coin are you mining on?

Nathaniel Hayes
President of the Simpson college Computer Science Club
(515) 357-3472

From: R4V3N-2010
Sent: Tuesday, February 13, 2018 11:07 AM
To: NanoBytesInc/Pickaxe
Cc: Subscribed
Subject: [NanoBytesInc/Pickaxe] Still keeps crashing on custom pool (#2)

The App crashed on if i choose Mining Pool Hub as pool.
Then i discovered that the app is also crashing on the pre filled pools.
I use a One Plus 3 with amr64-v8a architecture. Maybe you can take a look at it.

**Comment by R4V3N-2010** [comment]
That is strange cause I have a Qualcomm snapdragon 820. Hope you get it sorted out.
I treid to mine Electronium.

**Comment by NanoBytesInc** [comment]
What pool are you mining to?

Nathaniel Hayes
President of the Simpson college Computer Science Club
(515) 357-3472

**Comment by NanoBytesInc** [comment]
What pool are you mining to?

**Comment by R4V3N-2010** [comment]
Mining Pool Hub. Maybe you can add it to the list?

**Comment by NanoBytesInc** [comment]
It was originally on the  list, but I found that its lowest difficulty is just too high for mobile CPUs to work without timing out

**Comment by R4V3N-2010** [comment]
Ok. I did you come closer to solution with the crashes?

**Comment by NanoBytesInc** [comment]
Hopefully the latest update has corrected this!

**Comment by R4V3N-2010** [comment]
It works now as expected. Thanks for your hard work. Keep it up.
