### ISSUE TITLE
Wrong Label/Heading/Banner displayed for Bytecoin

### ISSUE THREAD

**Issue by kumarvarun1252** [NanoBytesInc/Pickaxe#5]
I am actually trying to mine bytecoin, but its actually displaying Screen heading/Label as Monero, which is confusing. Attached screenshot for your reference

![screenshot_20180219-215148](https://user-images.githubusercontent.com/8548710/36467080-f65d0704-1691-11e8-93da-0478b1fe8a84.png)

**Comment by NanoBytesInc** [comment]
Yeah, I just forgot to have that change per coin. You are mining Bytecoin 😊

Nathaniel Hayes
President of the Simpson college Computer Science Club
(515) 357-3472

From: Varun Mukka
Sent: Wednesday, February 21, 2018 1:01 AM
To: NanoBytesInc/Pickaxe
Cc: Subscribed
Subject: [NanoBytesInc/Pickaxe] Wrong Label/Heading displayed for Bytecoin(#5)

I am actually trying to mine bytecoin, but its actually displaying Screen heading/Label as Monero, which is confusing. Attached screenshot for your reference

**Comment by kumarvarun1252** [comment]
I see this issue in the latest/updated version of the app too.

**Comment by NanoBytesInc** [comment]
Yeah. The crashing part is where most of my work is going.

Honestly, all of the "coins" you select are the same on the back end (except Aeon). You can click moenro, and enter a Bytecoin pool and it will work exactly the same as were you to have clicked "Bytecoin" from the start

**Comment by kumarvarun1252** [comment]
Okay. Make sense, and this a low priority one. Less effect on mining, so this can be taken care ones all the major issues have been fixed.

**Comment by kumarvarun1252** [comment]
Do you want to create some labels like "Work In Progress", "High Priority", "Low Priority" etc, so that you don't need to worry about the minor issues for now? Makes your life easier while going through the issues
